#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/**
 * @see https://projecteuler.net:
 *
 * Highly divisible triangular number
 * Problem 12
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *     10: 1,2,5,10
 *     15: 1,3,5,15
 *     21: 1,3,7,21
 *     28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

unsigned long gaussSum(unsigned long nr)
{
    return nr * (nr + 1) / 2;
}

/**
 * Naïve approach to count divisors:
 * test nr / i, while i <= sqr(nr).
 * Not the fastest approach, but works in about 0.5s on my system, which is quite fine.
 *
 * Already at about 1000 divisors, the algorithm gets too slow. Another approach has to be found
 * for those large numbers of divisors.
 */
unsigned int countDivisors(unsigned long nr)
{
    unsigned long fact = 1;
    unsigned int counter = 0;
    ldiv_t dv;
    if (nr == 1)
    {
        return 1;
    }
    while (1)
    {
        dv = ldiv(nr, fact);
        if (dv.quot < fact)
        {
            break;
        }
        if (dv.rem == 0)
        {
            counter++;
            if (dv.quot > fact)
            {
                counter++;
            }
        }
        fact++;
    }
    return counter;
}

#define NR_OF_FACTORS 500

int main(void)
{
    unsigned int fCount = 0;
    unsigned long i = 1;
    while (1)
    {
        fCount = countDivisors(gaussSum(i));
        if (fCount > NR_OF_FACTORS)
        {
            printf("%lu: Sum: %lu, Facts: %d\n", i, gaussSum(i), fCount);
            break;
        }
        i++;
    }
}
