#include <stdio.h>

/**
 * @see https://projecteuler.net:
 *
 * Even Fibonacci numbers
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
int main(void) {
    // instead of using a recursive variant, I calculate it iteratively here, as we don't want to re-calculate the
    // whole sequence again for each new term:
    int a = 0;
    int b = 1;
    int act = 0;
    int sum = 0;
    while (act < 4000000) {
        if (act % 2 == 0) {
            sum += act;
        }
        act = a + b;
        a = b;
        b = act;
    }
    printf("Solution: %i\n", sum);
}
